# Generated by Django 4.2.7 on 2023-11-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friendshiprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendshipRequest',
        ),
    ]
